<?xml version="1.0" encoding="utf-8"?>

<Project>
  <Import Project="../Directory.Build.props" />
  <!-- test projects -->
  <PropertyGroup>
    <RootNamespace>Tests</RootNamespace>
    <NoWarn>$(NoWarn);1701;1702;EPS06</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Appveyor.TestLogger" Version="2.0.0" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
  </ItemGroup>
  <!-- xUnit v3 for .NET 8+ -->
  <ItemGroup
    Condition="'$(MSBuildProjectName.Contains(SharpArch.Tests.NHibernate))' == false">
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

    <Using Include="Xunit" />
    <Using Include="Moq" />
  </ItemGroup>
</Project>
