<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Lib\SharpArch.Domain\SharpArch.Domain.csproj" />
    <ProjectReference Include="..\..\Lib\SharpArch.Infrastructure\SharpArch.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Lib\SharpArch.Testing\SharpArch.Testing.csproj" />
  </ItemGroup>

</Project>
