<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="..\..\Common\AssemblyVersion.cs" Link="AssemblyVersion.cs" />
    <Compile Include="..\..\Common\NHibernate\TestDatabaseSetup.cs" Link="TestDatabaseSetup.cs" />
  </ItemGroup>

  <PropertyGroup Label="Pack">
    <Description>Provides base classes to help with testing applications written with Sharp Architecture using xUnit.</Description>
    <PackageTags>$(PackageTags);testing;xunit;db-testing;nhibernate</PackageTags>
    <IsTestProject>false</IsTestProject>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\Artefacts\Documentation\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup Label="Package References (xUnit v2 - netstandard2.1/net6.0)" Condition=" '$(TargetFramework)' == 'netstandard2.1' Or '$(TargetFramework)' == 'net6.0' ">
    <PackageReference Include="xunit.core" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup Label="Package References (xUnit v3 - .NET 8+)" Condition=" '$(TargetFramework)' == 'net8.0' Or '$(TargetFramework)' == 'net9.0' Or '$(TargetFramework)' == 'net10.0' ">
    <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpArch.Domain\SharpArch.Domain.csproj" />
    <ProjectReference Include="..\SharpArch.NHibernate\SharpArch.NHibernate.csproj" />
    <ProjectReference Include="..\SharpArch.Testing\SharpArch.Testing.csproj" />
  </ItemGroup>

  <PropertyGroup> <!-- override xunit setting -->
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

</Project>
