namespace Tests.SharpArch.SourceGenerators.DomainSignature.SourceGenerator;

using global::SharpArch.SourceGenerators.DomainSignature;
using global::SharpArch.SourceGenerators.DomainSignature.Impl;


public class SourceCodeGeneratorTests
{
    [Fact]
    public void Generate_IncludesCorrectUsingStatements()
    {
        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            new List<DomainSignaturePropertyInfo>(),
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        // Assert
        Assert.Contains("using System;", result);
        Assert.Contains("using System.Reflection;", result);
        Assert.Contains("using SharpArch.Domain.DomainModel;", result);
        Assert.Contains("using static global::", result);
        Assert.Contains("DomainSignatureComparerHelper;", result);
    }

    [Fact]
    public void Generate_IncludesCorrectXmlDocumentation()
    {
        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            new List<DomainSignaturePropertyInfo>(),
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        // Assert
        Assert.Contains("/// <summary>", result);
        Assert.Contains("/// Returns a hash code for this instance.", result);
        Assert.Contains("/// Determines whether the current object has the same object signature", result);
        Assert.Contains("/// <param name=\"compareTo\">The object to compare to.</param>", result);
    }

    [Fact]
    public void Generate_IncludesExcludeFromCodeCoverageAttribute()
    {
        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            new List<DomainSignaturePropertyInfo>(),
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        // Assert
        Assert.Contains("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage", result);
        Assert.Contains("Generated by the SharpArch.SourceGenerators.DomainSignature source generator", result);
    }

    [Fact]
    public void Generate_WithComplexNamespace_HandlesCorrectly()
    {
        var entity = new EntityInfo(
            "MyCompany.MyApp.Domain.Entities",
            "CustomerOrder",
            new List<DomainSignaturePropertyInfo> { new("OrderNumber", SignatureMemberType.Reference) },
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        // Assert
        Assert.Contains("namespace MyCompany.MyApp.Domain.Entities;", result);
        Assert.Contains("partial class CustomerOrder", result);
        Assert.Contains("var that = compareTo as CustomerOrder;", result);
    }

    [Fact]
    public void Generate_WithEightOrMoreProperties_UsesHashCodeAdd()
    {
        var properties = new List<DomainSignaturePropertyInfo>();
        for (int i = 1; i <= 8; i++)
        {
            properties.Add(new($"Property{i}", SignatureMemberType.Value));
        }

        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            properties,
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        // Assert
        Assert.Contains("var hashCode = new global::System.HashCode();", result);
        Assert.Contains("hashCode.Add(typeHashCode);", result);
        Assert.Contains("hashCode.Add(this.Property1);", result);
        Assert.Contains("hashCode.Add(this.Property8);", result);
        Assert.Contains("return hashCode.ToHashCode();", result);
        Assert.DoesNotContain("HashCode.Combine(", result);
    }

    [Fact]
    public void Generate_WithMixedPropertyTypes_GeneratesCorrectComparisonLogic()
    {
        var properties = new List<DomainSignaturePropertyInfo>
        {
            new("Id", SignatureMemberType.Value),
            new("Name", SignatureMemberType.Reference),
            new("OptionalDate", SignatureMemberType.NullableValue),
            new("Email", SignatureMemberType.Reference),
            new("Age", SignatureMemberType.Value)
        };

        var entity = new EntityInfo(
            "MyApp.Domain",
            "User",
            properties,
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        // Assert
        Assert.Contains("if (!this.Id.Equals(that.Id))", result);
        Assert.Contains("if (!ReferenceTypesEqual(this.Name, that.Name))", result);
        Assert.Contains("if (!NullableValueTypesEqual(this.OptionalDate, that.OptionalDate))", result);
        Assert.Contains("if (!ReferenceTypesEqual(this.Email, that.Email))", result);
        Assert.Contains("if (!this.Age.Equals(that.Age))", result);
        Assert.Contains("return true;", result);
    }

    [Fact]
    public void Generate_WithMultiplePropertiesLessThanEight_UsesHashCodeCombine()
    {
        var properties = new List<DomainSignaturePropertyInfo>
        {
            new("Id", SignatureMemberType.Value),
            new("Name", SignatureMemberType.Reference),
            new("OptionalValue", SignatureMemberType.NullableValue)
        };

        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            properties,
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        // Assert
        Assert.Contains("HashCode.Combine(GetType()", result);
        Assert.Contains(",this.Id", result);
        Assert.Contains(",this.Name", result);
        Assert.Contains(",this.OptionalValue", result);
        Assert.DoesNotContain("hashCode.Add(", result);
    }

    [Fact]
    public void Generate_WithNoProperties_GeneratesBaseHashCodeAndEquals()
    {
        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            new List<DomainSignaturePropertyInfo>(),
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        // Assert
        Assert.Contains("namespace TestNamespace;", result);
        Assert.Contains("partial class TestEntity", result);
        Assert.Contains("return base.GetHashCode();", result);
        Assert.Contains("return base.Equals(compareTo);", result);
        Assert.Contains("// No properties were flagged with DomainSignatureAttribute", result);
    }

    [Fact]
    public void Generate_WithSingleNullableValueTypeProperty_GeneratesCorrectCode()
    {
        var properties = new List<DomainSignaturePropertyInfo> { new("OptionalId", SignatureMemberType.NullableValue) };

        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            properties,
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        // Assert
        Assert.Contains("if (!NullableValueTypesEqual(this.OptionalId, that.OptionalId))", result);
    }

    [Fact]
    public void Generate_WithSingleReferenceTypeProperty_GeneratesCorrectCode()
    {
        var properties = new List<DomainSignaturePropertyInfo> { new("Name", SignatureMemberType.Reference) };

        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            properties,
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        // Assert
        Assert.Contains("if (!ReferenceTypesEqual(this.Name, that.Name))", result);
    }

    [Fact]
    public void Generate_WithSingleValueTypeProperty_GeneratesCorrectCode()
    {
        var properties = new List<DomainSignaturePropertyInfo> { new("Id", SignatureMemberType.Value) };

        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            properties,
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        // Assert
        Assert.Contains("namespace TestNamespace;", result);
        Assert.Contains("partial class TestEntity", result);
        Assert.Contains("HashCode.Combine(GetType()", result);
        Assert.Contains(",this.Id", result);
        Assert.Contains("if (!this.Id.Equals(that.Id))", result);
        Assert.Contains("var that = compareTo as TestEntity;", result);
    }
}
