namespace Tests.SharpArch.SourceGenerators.DomainSignature.SourceGenerator;

using global::SharpArch.SourceGenerators.DomainSignature;
using global::SharpArch.SourceGenerators.DomainSignature.Impl;
using Shouldly;


public class SourceCodeGeneratorTests
{
    [Fact]
    public void Generate_IncludesCorrectUsingStatements()
    {
        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            new List<DomainSignaturePropertyInfo>(),
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        result.ShouldContain("using System;");
        result.ShouldContain("using SharpArch.Domain.DomainModel;");
        result.ShouldContain("using static global::");
        result.ShouldContain("DomainSignatureComparerHelper;");
    }

    [Fact]
    public void Generate_WithRecordKind_EmitsPartialRecord()
    {
        var entity = new EntityInfo(
            "TestNamespace",
            "TestRecord",
            new List<DomainSignaturePropertyInfo> { new("Id", SignatureMemberType.Value) },
            true,
            true,
            isRecord: true);

        var result = SourceCodeGenerator.Generate(entity);

        result.ShouldContain("partial record TestRecord");
        result.ShouldNotContain("partial class TestRecord");
    }

    [Fact]
    public void Generate_IncludesCorrectXmlDocumentation()
    {
        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            new List<DomainSignaturePropertyInfo>(),
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        result.ShouldContain("/// <summary>");
        result.ShouldContain("/// Returns a hash code for this instance.");
        result.ShouldContain("/// Determines whether the current object has the same object signature");
        result.ShouldContain("/// <param name=\"compareTo\">The object to compare to.</param>");
    }

    [Fact]
    public void Generate_IncludesExcludeFromCodeCoverageAttribute()
    {
        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            new List<DomainSignaturePropertyInfo>(),
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        result.ShouldContain("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage");
        result.ShouldContain("Generated by the SharpArch.SourceGenerators.DomainSignature source generator");
    }

    [Fact]
    public void Generate_WithComplexNamespace_HandlesCorrectly()
    {
        var entity = new EntityInfo(
            "MyCompany.MyApp.Domain.Entities",
            "CustomerOrder",
            new List<DomainSignaturePropertyInfo> { new("OrderNumber", SignatureMemberType.Reference) },
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        result.ShouldContain("namespace MyCompany.MyApp.Domain.Entities;");
        result.ShouldContain("partial class CustomerOrder");
        result.ShouldContain("var that = compareTo as CustomerOrder;");
    }

    [Fact]
    public void Generate_WithEightOrMoreProperties_UsesHashCodeAdd()
    {
        var properties = new List<DomainSignaturePropertyInfo>();
        for (int i = 1; i <= 8; i++)
        {
            properties.Add(new($"Property{i}", SignatureMemberType.Value));
        }

        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            properties,
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        result.ShouldContain("var hashCode = new global::System.HashCode();");
        result.ShouldContain("hashCode.Add(typeHashCode);");
        result.ShouldContain("hashCode.Add(this.Property1);");
        result.ShouldContain("hashCode.Add(this.Property8);");
        result.ShouldContain("return hashCode.ToHashCode();");
        result.ShouldNotContain("HashCode.Combine(");
    }

    [Fact]
    public void Generate_WithMixedPropertyTypes_GeneratesCorrectComparisonLogic()
    {
        var properties = new List<DomainSignaturePropertyInfo>
        {
            new("Id", SignatureMemberType.Value),
            new("Name", SignatureMemberType.Reference),
            new("OptionalDate", SignatureMemberType.NullableValue),
            new("Email", SignatureMemberType.Reference),
            new("Age", SignatureMemberType.Value)
        };

        var entity = new EntityInfo(
            "MyApp.Domain",
            "User",
            properties,
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        result.ShouldContain("if (!this.Id.Equals(that.Id))");
        result.ShouldContain("if (!ReferenceTypesEqual(this.Name, that.Name))");
        result.ShouldContain("if (!NullableValueTypesEqual(this.OptionalDate, that.OptionalDate))");
        result.ShouldContain("if (!ReferenceTypesEqual(this.Email, that.Email))");
        result.ShouldContain("if (!this.Age.Equals(that.Age))");
        result.ShouldContain("return true;");
    }

    [Fact]
    public void Generate_WithMultiplePropertiesLessThanEight_UsesHashCodeCombine()
    {
        var properties = new List<DomainSignaturePropertyInfo>
        {
            new("Id", SignatureMemberType.Value),
            new("Name", SignatureMemberType.Reference),
            new("OptionalValue", SignatureMemberType.NullableValue)
        };

        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            properties,
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        result.ShouldContain("HashCode.Combine(GetType()");
        result.ShouldContain(",this.Id");
        result.ShouldContain(",this.Name");
        result.ShouldContain(",this.OptionalValue");
        result.ShouldNotContain("hashCode.Add(");
    }

    [Fact]
    public void Generate_WithNoProperties_GeneratesBaseHashCodeAndEquals()
    {
        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            new List<DomainSignaturePropertyInfo>(),
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        result.ShouldContain("namespace TestNamespace;");
        result.ShouldContain("partial class TestEntity");
        result.ShouldContain("return base.GetHashCode();");
        result.ShouldContain("return base.Equals(compareTo);");
        result.ShouldContain("// No properties were flagged with DomainSignatureAttribute");
    }

    [Fact]
    public void Generate_WithSingleNullableValueTypeProperty_GeneratesCorrectCode()
    {
        var properties = new List<DomainSignaturePropertyInfo> { new("OptionalId", SignatureMemberType.NullableValue) };

        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            properties,
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        result.ShouldContain("if (!NullableValueTypesEqual(this.OptionalId, that.OptionalId))");
    }

    [Fact]
    public void Generate_WithSingleReferenceTypeProperty_GeneratesCorrectCode()
    {
        var properties = new List<DomainSignaturePropertyInfo> { new("Name", SignatureMemberType.Reference) };

        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            properties,
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        result.ShouldContain("if (!ReferenceTypesEqual(this.Name, that.Name))");
    }

    [Fact]
    public void Generate_WithSingleValueTypeProperty_GeneratesCorrectCode()
    {
        var properties = new List<DomainSignaturePropertyInfo> { new("Id", SignatureMemberType.Value) };

        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            properties,
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        result.ShouldContain("namespace TestNamespace;");
        result.ShouldContain("partial class TestEntity");
        result.ShouldContain("HashCode.Combine(GetType()");
        result.ShouldContain(",this.Id");
        result.ShouldContain("if (!this.Id.Equals(that.Id))");
        result.ShouldContain("var that = compareTo as TestEntity;");
    }

    [Fact]
    public void Generate_DoesNotEmitUnusedSystemReflectionUsing()
    {
        var entity = new EntityInfo(
            "TestNamespace",
            "TestEntity",
            new List<DomainSignaturePropertyInfo> { new("Id", SignatureMemberType.Value) },
            true,
            true);

        var result = SourceCodeGenerator.Generate(entity);

        result.ShouldNotContain("using System.Reflection;");
        result.ShouldContain("using System;");
    }
}