namespace SharpArch.SourceGenerators.DomainSignature.Impl;

static class SourceCodeGeneratorHelper
{
    internal const string GeneratorName = "SharpArch.SourceGenerators.DomainSignature";
    internal const string InternalNamespace = "SharpArch.SourceGenerators.DomainSignature.Internal";

    internal const string Header =
        $$"""
                                  
          //------------------------------------------------------------------------------
          // <auto-generated>
          //     This code was generated by the {{GeneratorName}} source generator
          //
          //     Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
          // </auto-generated>
          //------------------------------------------------------------------------------
          #nullable enable
          """;

    internal static string DomainSignatureComparerHelper =>
        $$"""
          {{Header}}

          namespace {{InternalNamespace}};
          
          using System.Runtime.CompilerServices;

          internal static class DomainSignatureComparerHelper                  
          {
              [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
              public static bool ReferenceTypesEqual<T>(T? left, T? right)
                  where T : class
              {
                  if (left is null && right is null)
                      return true;
                  if (left is null || right is null)
                      return false;
                  
                  return left.Equals(right);
              }
              
              [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
              public static bool NullableValueTypesEqual<T>(in T? left, in T? right)
                  where T : struct
              {
                  if (left is null && right is null)
                      return true;
                  if (left is null || right is null)
                      return false;
                      
                  return left.Value.Equals(right.Value);
              }
          }
          """;

}
