<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Build">
    <!-- Registration helpers are not expected to be used by generic-purpose library  -->
    <TargetFrameworks>$(AppTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\Common\AssemblyVersion.cs" Link="AssemblyVersion.cs" />
  </ItemGroup>

  <PropertyGroup Label="Pack">
    <Description>Add NHibernate registration helpers for Microsoft Dependency Injecton.</Description>
    <PackageTags>$(PackageTags);dependency-injection</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\Artefacts\Documentation\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup Label="Package References (.NET 8)" Condition=" '$(TargetFramework)' == 'net8.0' ">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup Label="Package References (.NET 9)" Condition=" '$(TargetFramework)' == 'net9.0' ">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup Label="Package References (.NET 10)" Condition=" '$(TargetFramework)' == 'net10.0' ">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpArch.Domain\SharpArch.Domain.csproj" />
    <ProjectReference Include="..\SharpArch.Infrastructure\SharpArch.Infrastructure.csproj" />
    <ProjectReference Include="..\SharpArch.NHibernate\SharpArch.NHibernate.csproj" />
  </ItemGroup>


</Project>
