namespace SharpArch.SourceGenerators.DomainSignature;

using Impl;
using System.Text;

/// <summary>
/// Generates source code for domain signature implementation based on entity information.
/// </summary>
static class SourceCodeGenerator
{
    /// <summary>
    /// Generates the source code for the domain signature implementation.
    /// </summary>
    /// <param name="entity">Information about the entity for which to generate code.</param>
    /// <returns>The generated source code as a string.</returns>

    public static string Generate(EntityInfo entity)
    {
        var namespaceName = entity.ClassNamespace;
        var className = entity.ClassName;

        var source = new StringBuilder(8 * 1024);

        // Add namespace and usings
        source.AppendLine(SourceCodeGeneratorHelper.Header);
        source.AppendLine();
        source.AppendLine("using System;");
        source.AppendLine("using SharpArch.Domain.DomainModel;");
        source.AppendLine($"using static global::{SourceCodeGeneratorHelper.InternalNamespace}.DomainSignatureComparerHelper;");
        source.AppendLine();

        // Begin namespace (file-scoped)
        source.AppendLine($"namespace {namespaceName};");
        source.AppendLine();

        // Begin class declaration (preserve record vs class kind)
        source.AppendLine($"partial {(entity.IsRecord ? "record" : "class")} {className}");
        source.AppendLine("{");

        // Add GetHashCode override
        source.AppendLine("    /// <summary>");
        source.AppendLine("    /// Returns a hash code for this instance.");
        source.AppendLine("    /// </summary>");
        source.AppendLine("    /// <returns>");
        source.AppendLine("    /// A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table.");
        source.AppendLine("    /// </returns>");
        source.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = \"Generated by the SharpArch.SourceGenerators.DomainSignature source generator.\")]");
        source.AppendLine("    public override int GetHashCode()");
        source.AppendLine("    {");
        source.AppendLine("        unchecked");
        source.AppendLine("        {");

        if (entity.DomainSignatureProperties.Count == 0)
        {
            source.AppendLine("            // No properties were flagged with DomainSignatureAttribute");
            source.AppendLine("            return base.GetHashCode();");
        }
        else
        {
            source.AppendLine("            // It's possible for two objects to return the same hash code based on");
            source.AppendLine("            // identically valued properties, even if they're of two different types,");
            source.AppendLine("            // so we include the object's type in the hash calculation");
            // HashCode.Combine can accept up to 8 arguments, so we handle that case separately
            if (entity.DomainSignatureProperties.Count < 8)
            {
                source.AppendLine("             return HashCode.Combine(GetType()");
                foreach (var property in entity.DomainSignatureProperties)
                {
                    source.AppendLine($"                ,this.{property.Name}");
                }

                source.AppendLine("            );");
            }
            else
            {
                source.AppendLine("            int typeHashCode = GetType().GetHashCode();");
                source.AppendLine("            var hashCode = new global::System.HashCode();");
                source.AppendLine("            hashCode.Add(typeHashCode);");
                source.AppendLine();

                foreach (var property in entity.DomainSignatureProperties)
                {
                    source.AppendLine($"            hashCode.Add(this.{property.Name});");
                }

                source.AppendLine("            return hashCode.ToHashCode();");
            }

        }

        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();

        // Add HasSameObjectSignatureAs override
        source.AppendLine("    /// <summary>");
        source.AppendLine("    /// Determines whether the current object has the same object signature as the specified object.");
        source.AppendLine("    /// </summary>");
        source.AppendLine("    /// <param name=\"compareTo\">The object to compare to.</param>");
        source.AppendLine("    /// <returns>");
        source.AppendLine("    /// <c>true</c> if the current object has the same object signature as the specified object; otherwise, <c>false</c>.");
        source.AppendLine("    /// </returns>");
        source.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = \"Generated by the SharpArch.SourceGenerators.DomainSignature source generator.\")]");
        source.AppendLine("    public override bool HasSameObjectSignatureAs(BaseObject compareTo)");
        source.AppendLine("    {");

        if (entity.DomainSignatureProperties.Count == 0)
        {
            source.AppendLine("        // No properties were flagged with DomainSignatureAttribute");
            source.AppendLine("        // ReSharper disable once BaseObjectEqualsIsObjectEquals");
            source.AppendLine("        return base.Equals(compareTo);");
        }
        else
        {
            source.AppendLine($"        var that = compareTo as {className};");
            source.AppendLine("        if (that == null)");
            source.AppendLine("            return false;");
            source.AppendLine();

            foreach (var property in entity.DomainSignatureProperties)
            {
                var propName = property.Name;
                if (property.MemberType == SignatureMemberType.Reference)
                {
                    source.AppendLine($"        if (!ReferenceTypesEqual(this.{propName}, that.{propName}))");
                }
                else if (property.MemberType == SignatureMemberType.NullableValue)
                {
                    source.AppendLine($"        if (!NullableValueTypesEqual(this.{propName}, that.{propName}))");
                }
                else // value type
                {
                    source.AppendLine($"        if (!this.{propName}.Equals(that.{propName}))");
                }
                source.AppendLine( "            return false;");
            }

            source.AppendLine();
            source.AppendLine("        return true;");
        }

        source.AppendLine("    }");

        // End class
        source.AppendLine("}");

        return source.ToString();
    }
}