title: S#arp Architecture
description: A solid architectural foundation for rapidly building maintainable ASP.NET Core web applications with NHibernate.
theme: jekyll-theme-cayman
show_downloads: false
